using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
public class CameraXuanru : MonoBehaviour
{
    public float SensX = 400;// Sensitivity multiplier for horizontal rotation.
    public float SensY = 400;

    public Transform Orientation;// Reference to the transform used to orient the camera in space, not used in this snippet.
    public Transform playerTransform;

    private float xRotation = 0f;
    private float yRotation = 0f;

    private PlayerControls controls;// Variable to store the instance of the PlayerControls generated by the Input System.

    private void Awake() {
        controls = new PlayerControls();
        controls.Gameplay.Rotate.performed += ctx => {
            Vector2 input = ctx.ReadValue<Vector2>();
            xRotation = Mathf.Clamp(xRotation - input.y * SensY * Time.deltaTime, -90f, 90f);  // Limit vertical rotation
            yRotation += input.x * SensX * Time.deltaTime;  // Horizontal rotation
        };
    }

    private void Update()
    {
        Quaternion horizontalRotation = Quaternion.Euler(0, yRotation, 0);
        Quaternion verticalRotation = Quaternion.Euler(xRotation, 0, 0);
        transform.rotation = Quaternion.Lerp(transform.rotation, horizontalRotation * verticalRotation, Time.deltaTime * 10);// Smoothly interpolate between the current rotation and the target rotation using Lerp.
    }


    private void OnEnable()
    {
        controls.Gameplay.Enable();// Enable the Gameplay map of the PlayerControls when the script component is enabled.
    }
    

    private void OnDisable()
    {
        controls.Gameplay.Disable();// Disable the Gameplay map of the PlayerControls when the script component is disabled.
    }
}